services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - /data/kavita/config:/kavita/config
      - /data/kavita/manga:/manga
      - /data/kavita/comics:/comics
      - /data/kavita/books:/books
    environment:
      - TZ=America/Guatemala
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`books.aicycle.cloud`)
      - traefik.http.routers.kavita.entrypoints=websecure
      - traefik.http.routers.kavita.tls.certResolver=letsencrypt
      - traefik.http.services.kavita.loadbalancer.server.port=5000

networks:
  dokploy-network:
    external: true
